import { Playfair, Montserrat , DM_Serif_Text } from "next/font/google"
import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const playfair = Playfair({
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', "800", "900"],
  variable: "--font-playfair",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", '300', '400', '500', '600', '700', "800", "900"],
  variable: "--font-montserrat",
});

const dmSerifText = DM_Serif_Text({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-dm-serif-text",
});

export const metadata = {
  title: "Automotive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfair.className} ${montserrat.variable} ${dmSerifText.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
      <BootstrapClient />
    </html>
  );
}
